# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 311a34f6db69786da7d0916c24e2a58f8e12039e9eb8761492a7bedfcd53178c1ff3f03bcede5cc8bb94defcea99f5dc1b7d0acac1904fecc318776e23461fc2

test:
  secret_key_base: 07167658bae2a25410dc7458068ca7a6793ab990de49c81684f36d9ea261a6c7ec1c4ad11f7b3ee19bf62ac02f7404bf2418eddbae00456f4c43bf868a2aefb1

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
